### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by bdrung** [d2r2/go-logger#5]
There is no copyright information in the git repository, neither license headers in the go files nor a separate license file. Please add license headers and a LICENSE file. Missing information means that no permission are granted.

**Comment by d2r2** [comment]
@bdrung, completely agree with you. I will add MIT license to this package during a week. Thanks for mentioning this!

**Comment by bdrung** [comment]
Any updates on this?

**Comment by d2r2** [comment]
Hi @bdrung! Sorry for long delay (I have too much work to do) :(
I promise, I'll fix it before the end of this week. I will inform you additionally.

**Comment by d2r2** [comment]
> Any updates on this?

Hi @bdrung. I have implemented the requested update.
